[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "face-recognition",
    "opencv-python",
    "numpy",
    "transformers>=4.49.0",
    "turtles>=1.0.0",
    "pytube",
    "flask",
]